(defun calculate (operator num1 num2)
  (cond ((equal operator '+) (+ num1 num2))
        ((equal operator '-) (- num1 num2))
        ((equal operator '*) (* num1 num2))
        ((equal operator '/) (/ num1 num2))
        (t (format nil "Unknown operator: ~a" operator))))

(defun start-calculator ()
  (format t "Simple Lisp Calculator~%")
  (loop
    (format t "Enter an operator (+, -, *, /) or 'quit' to exit: ")
    (let ((input (read)))
      (when (equal input 'quit)
        (return))
      (format t "Enter the first number: ")
      (let ((num1 (read)))
        (format t "Enter the second number: ")
        (let ((num2 (read)))
          (format t "Result: ~a~%" (calculate input num1 num2)))))))
